name: acquiacms
recipe: drupal8
config:
  webroot: docroot
  database: mariadb
services:
  appserver:
    xdebug: false
    build:
      - bash ./scripts/clone-repos
      - composer install
    run:
      - blt setup -n
    overrides:
      image: 'acquia/ads-local:lando-php-7.3-nodejs-10'
      cap_add:
        - SYS_ADMIN
  phpmyadmin:
    type: phpmyadmin
  memcached:
    type: 'memcached:1.5.3-r1'
env_file:
  - ./.lando/local.env
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  drush:
    cmd: /app/vendor/bin/drush --uri=acquiacms.lndo.site --root=/app/docroot
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
