version: "2.1"

services:
  # Add your service overrides here.
  # Expose Solr on a Virtualhost.
  #solr:
  #  labels:
  #    - io.docksal.virtual-host=solr.${VIRTUAL_HOST}
  #    - io.docksal.virtual-port=8983

  chrome:
    hostname: chrome
    # We're using older headless chrome that still allows access to debugging
    # from non-localhost hostname, as it was patched in https://bugs.chromium.org/p/chromium/issues/detail?id=813540
    image: yukinying/chrome-headless-browser:64.0.3282.24
    shm_size: 512M
    cap_add:
      - SYS_ADMIN
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
